### ISSUE TITLE
Seems that the protobuf being used is out of date

### ISSUE THREAD

**Issue by diasdavid** [libp2p/go-floodsub#17]
The latest iteration is: https://github.com/libp2p/pubsub-notes/blob/master/flooding/flooding.proto, while https://github.com/libp2p/go-floodsub/blob/master/pb/rpc.proto is the first commit of that protobuf. 

@whyrusleeping could you update

**Comment by whyrusleeping** [comment]
What is the difference? It's hard to tell just quickly looking at them

**Comment by diasdavid** [comment]
https://github.com/libp2p/pubsub-notes/blob/master/flooding/flooding.proto#L9
vs
https://github.com/libp2p/go-floodsub/blob/master/pb/rpc.proto#L9

and 
https://github.com/libp2p/pubsub-notes/blob/master/flooding/flooding.proto#L16
vs
https://github.com/libp2p/go-floodsub/blob/master/pb/rpc.proto#L17

**Comment by whyrusleeping** [comment]
Eh, thats a breaking change on my end. And doesnt break any sort of compatibility between us. I'll mark this as a todo and make the change when we have other more important protobuf changes to deal with.

**Comment by Kubuxu** [comment]
I don't think that delaying it more will be helpful, the uses of floodsub will only increase, currently it isn't in any official release. I know that it won't be pain free but it will cause less pain to do it now (before any release) than latter.

**Comment by whyrusleeping** [comment]
Oh, hold on. Its not even a breaking change. What are we worried about? The protobuf IDs are the same, the names don't matter. I can change them all to various names of superheros if I really wanted to and the protocol would still work fine.

**Comment by dignifiedquire** [comment]
![giphy-2](https://cloud.githubusercontent.com/assets/790842/21403482/39d2c82c-c7bd-11e6-830d-f2a50c51556a.gif)

**Comment by diasdavid** [comment]
Right, that is why we had it working in NYC :)

Well, would be great to have it up to date to avoid confusion, but nvm then :)

**Comment by whyrusleeping** [comment]
Yeah, we can update it. It won't change anything important
