### ISSUE TITLE
PubSub sometimes failing

### ISSUE THREAD

**Issue by richardschneider** [libp2p/go-floodsub#52]
[C# test](https://github.com/richardschneider/net-ipfs-api/blob/master/test/CoreApi/PubSubApiTest.cs#L97) and [JS test](https://github.com/ipfs/interface-ipfs-core/blob/master/src/pubsub.js#L496) are intermittently failing.  Both are  publishing multiple messages and then counting the subscribed messages. 

It appears that some published messages are not being relayed to the subscribed channels. In the C# test both publisher and subscriber are on the same peer.

NOTE: these tests are running on Windows.  This was first detected in https://github.com/ipfs/js-ipfs-api/pull/648

**Comment by richardschneider** [comment]
[this code](https://github.com/libp2p/go-floodsub/blob/master/floodsub.go#L418) looks suspicious

> binary.BigEndian.PutUint64(seqno, uint64(time.Now().UnixNano())) 

A duplicate sequence number can be produced when a second  publish event is received within the resolution of the clock.  If this occurs, then the second publish event will not be relayed.

On Windows, the default clock resolution is 15.6 ms, but it appears [go changes](https://github.com/golang/go/issues/8687) it to 1ms.  This is more that adequate to produce a duplicate sequence number.

**Comment by Stebalien** [comment]
Yes, that looks like a bug. We should just use an atomic counter (maybe start at the current unix time to better handle restarts).

**Comment by richardschneider** [comment]
@Stebalien Or maybe concatenating the time with an atomic counter.

**Comment by Stebalien** [comment]
@richardschneider good point (I thought we had to try to fit this into a 64bit int but apparently not).

**Comment by vyzo** [comment]
Yeah, the 1ms resolution is not enough for real-time or bursty applications; definitely a bug.
