### ISSUE TITLE
Possible deadlock

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-floodsub#63]
When creating a small cluster of PubSub's around a topic in some test code I wrote, I found I needed to add a little `time.Sleep` just after the calls to `Subscribe()`.

`Subscribe()` returns right away with a subscription and a nil error, however, if I don't sleep a bit, calling `subscription.Next()` blocked forever.  Could this be a deadlock issue?

**Comment by Stebalien** [comment]
Interesting... I don't see how sleeping there could make a difference. Would it be possible for you to post your code?

**Comment by jvsteiner** [comment]
QmQotsmrxHUU17SNQX1VQRVFW9WLNDzbnf3bfYPSU3fGyL :)  Take the sleeps out and play a bit.   It was more pronounced before I added the handler functions - I think the function calls affected the event loop a bit, but it still happens - maybe sometimes only one message comes through.  If you's like a more conventional delivery, or a minimal example, i can do that too - might take a bit more time.

**Comment by Stebalien** [comment]
Um. So... how *exactly* did you add that directory to IPFS? You managed to add it with the name "." which really shouldn't be possible (i.e., it's a bug and we need to fix it).

**Comment by Stebalien** [comment]
So, looking at the code, you *will* need to sleep between subscribing and *publishing*. Pubsub is asynchronous and unreliable (intentionally) so, if you subscribe on one peer and then immediately publish on another, the first peer may not get the message because the second may not have gotten the subscription yet.

We *are* looking into ways to make it possible to catch up on missed messages but we still haven't agreed on a generalizable way that isn't horribly inefficient. See #42.

**Comment by Stebalien** [comment]
@jvsteiner asside, I've published a new version of go-libp2p (5.0.13, QmT68EgyFbnSs5rbHkNkFZQwjdHfqrJiGr3R6rwcwnzYLc) so you don't have to use your custom release.

**Comment by jvsteiner** [comment]
on the Multihash above - I added it using `gx publish` - this was the hash that command returned.  I've got ipfs v0.4.13 (installed via homebrew) and gx v0.12.1

On the rest - yup, makes sense - Thanks.

**Comment by jvsteiner** [comment]
I reproduced the behavior with "." in another directory using `gx init .` - I gather in gx I would usually assign the package a name this way, but I typed "." out of git muscle memory.  Of course, that doesn't explain how _gx_ was able to create that directory, but hopefully it gets you somewhere.

**Comment by Stebalien** [comment]
That does. Thanks!
