### ISSUE TITLE
Can't remove a topic validator

### ISSUE THREAD

**Issue by bejito** [libp2p/go-floodsub#68]
Hi !
I might be missing something, but I cannot find a way to unregister a topic validator.
Indeed, in my case I have multiple services that use the floodsub layer. A service subscribes to a topic and registers a validator for that topic. When stopping the service, I can call `Cancel()` on the `Subscribtion`, but there is no way to remove the topic validator from `Pubsub.topicVals`.

Maybe I am doing this wrong, but it feels necessary to have one of these:
- unregister the topic validator when canceling the subscription (not good IMO as you might want to set the validator once only at launch and then register/unregister as much as you want)
- expose a method to clean the validator for a given topic.

**Comment by vyzo** [comment]
You are right, there is currently no mechanism to unregister a validator -- and that's an oversight.
We have rejected per subscription validators, but we can certainly expose a method to clear the validator.

**Comment by bejito** [comment]
Thank you for your answer @vyzo. Do you want me to make a PR to add that ? I am going to need this pretty quickly so I'll have to do it anyway and it doesn't seem too complicated.

**Comment by vyzo** [comment]
I can add it, it wont take long.

**Comment by vyzo** [comment]
Implemented in #70.

**Comment by bejito** [comment]
Awesome ! Is there a gx publish planned ?

**Comment by vyzo** [comment]
@Stebalien what's our plans for gx publish?

**Comment by vyzo** [comment]
#71 gx publishes.
