### ISSUE TITLE
Slow subscriptions can block the event loop

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-floodsub#69]
The event loop dispatches messages to subscriptions in `notifySubs`, which puts the new message to the subscription's channel.
This channel is buffered for 32 messages, and then the put will block -- which blocks the entire event loop.

Still not sure if this is a bug or a feature, but i don't like slow subscribers blocking the router. Sadly, there is no good solution to the problem, other than dropping messages on overflow just like we do with our output channels.

@Stebalien @whyrusleeping thoughts on the issue?

**Comment by whyrusleeping** [comment]
@vyzo it should be dropping messages if the buffered channel is full. Is this no longer happening?

**Comment by Stebalien** [comment]
We do that with *peers* but not local subscriptions. However, IMO, dropping messages sounds reasonable.

**Comment by vyzo** [comment]
i think we should fix it to drop messages, in light of these observations; adding to the queue for post gossisupb work.

**Comment by vyzo** [comment]
I am actually hitting this occasionally in a gossipsub test that overloads the queue; i think i will fix it in the gossipsub pr.

**Comment by whyrusleeping** [comment]
@vyzo oh please don't make that PR bigger. Lets try and merge as many small pieces of it separately as we can.

**Comment by vyzo** [comment]
sure, I'll cherry pick the commits and make a new PR.
