### ISSUE TITLE
Floodsub warning: no syntax specified for the proto file

### ISSUE THREAD

**Issue by jamesray1** [libp2p/go-floodsub#85]
> ```
> protoc --rust_out . rpc.proto
> [libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: rpc.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
> ```

https://github.com/libp2p/rust-libp2p/issues/287

**Comment by prestonvanloon** [comment]
This should be proto3. I'll send a PR

**Comment by prestonvanloon** [comment]
On second thought, this is already using proto2 as the default and other projects have the same file so it would mean updating many projects to proto3. 

Possibility a breaking change, so I'll submit a different PR to set the syntax explicitly to proto2 and that will silence the warning.

**Comment by Stebalien** [comment]
Closed in #88.
